# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 024ade19598109b738cdc9331a24ad39d0c4fcadcb283bb30b84eed67653508f73b328f9b14e68f87fd4631d1ba34e00fd3537e04c6e1535d6fb0dbd789eeb18

test:
  secret_key_base: 07f586ebf69f2ee41a94305e518821f2d80905e22ecb1a4953413fef3ff582f8c0f792b19a5df879393d8701bf23f885c9ffc243025ecb77a327f001c3727519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
